*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZADOV_GRAINS_020................................*
FORM GET_DATA_ZADOV_GRAINS_020.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADOT_GRAINS_020 WHERE
(VIM_WHERETAB) .
    CLEAR ZADOV_GRAINS_020 .
ZADOV_GRAINS_020-MANDT =
ZADOT_GRAINS_020-MANDT .
ZADOV_GRAINS_020-COMPANY_CODE =
ZADOT_GRAINS_020-COMPANY_CODE .
ZADOV_GRAINS_020-APP_CODE =
ZADOT_GRAINS_020-APP_CODE .
ZADOV_GRAINS_020-COMMODITY =
ZADOT_GRAINS_020-COMMODITY .
ZADOV_GRAINS_020-PROFIT_CENTER =
ZADOT_GRAINS_020-PROFIT_CENTER .
ZADOV_GRAINS_020-TRANSITORY_ACCOUNT =
ZADOT_GRAINS_020-TRANSITORY_ACCOUNT .
<VIM_TOTAL_STRUC> = ZADOV_GRAINS_020.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADOV_GRAINS_020 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADOV_GRAINS_020.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADOV_GRAINS_020-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADOT_GRAINS_020 WHERE
  COMPANY_CODE = ZADOV_GRAINS_020-COMPANY_CODE AND
  APP_CODE = ZADOV_GRAINS_020-APP_CODE AND
  COMMODITY = ZADOV_GRAINS_020-COMMODITY AND
  PROFIT_CENTER = ZADOV_GRAINS_020-PROFIT_CENTER AND
  TRANSITORY_ACCOUNT = ZADOV_GRAINS_020-TRANSITORY_ACCOUNT .
    IF SY-SUBRC = 0.
    DELETE ZADOT_GRAINS_020 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADOT_GRAINS_020 WHERE
  COMPANY_CODE = ZADOV_GRAINS_020-COMPANY_CODE AND
  APP_CODE = ZADOV_GRAINS_020-APP_CODE AND
  COMMODITY = ZADOV_GRAINS_020-COMMODITY AND
  PROFIT_CENTER = ZADOV_GRAINS_020-PROFIT_CENTER AND
  TRANSITORY_ACCOUNT = ZADOV_GRAINS_020-TRANSITORY_ACCOUNT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADOT_GRAINS_020.
    ENDIF.
ZADOT_GRAINS_020-MANDT =
ZADOV_GRAINS_020-MANDT .
ZADOT_GRAINS_020-COMPANY_CODE =
ZADOV_GRAINS_020-COMPANY_CODE .
ZADOT_GRAINS_020-APP_CODE =
ZADOV_GRAINS_020-APP_CODE .
ZADOT_GRAINS_020-COMMODITY =
ZADOV_GRAINS_020-COMMODITY .
ZADOT_GRAINS_020-PROFIT_CENTER =
ZADOV_GRAINS_020-PROFIT_CENTER .
ZADOT_GRAINS_020-TRANSITORY_ACCOUNT =
ZADOV_GRAINS_020-TRANSITORY_ACCOUNT .
    IF SY-SUBRC = 0.
    UPDATE ZADOT_GRAINS_020 ##WARN_OK.
    ELSE.
    INSERT ZADOT_GRAINS_020 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADOV_GRAINS_020-UPD_FLAG,
STATUS_ZADOV_GRAINS_020-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADOV_GRAINS_020.
  SELECT SINGLE * FROM ZADOT_GRAINS_020 WHERE
COMPANY_CODE = ZADOV_GRAINS_020-COMPANY_CODE AND
APP_CODE = ZADOV_GRAINS_020-APP_CODE AND
COMMODITY = ZADOV_GRAINS_020-COMMODITY AND
PROFIT_CENTER = ZADOV_GRAINS_020-PROFIT_CENTER AND
TRANSITORY_ACCOUNT = ZADOV_GRAINS_020-TRANSITORY_ACCOUNT .
ZADOV_GRAINS_020-MANDT =
ZADOT_GRAINS_020-MANDT .
ZADOV_GRAINS_020-COMPANY_CODE =
ZADOT_GRAINS_020-COMPANY_CODE .
ZADOV_GRAINS_020-APP_CODE =
ZADOT_GRAINS_020-APP_CODE .
ZADOV_GRAINS_020-COMMODITY =
ZADOT_GRAINS_020-COMMODITY .
ZADOV_GRAINS_020-PROFIT_CENTER =
ZADOT_GRAINS_020-PROFIT_CENTER .
ZADOV_GRAINS_020-TRANSITORY_ACCOUNT =
ZADOT_GRAINS_020-TRANSITORY_ACCOUNT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADOV_GRAINS_020 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADOV_GRAINS_020-COMPANY_CODE TO
ZADOT_GRAINS_020-COMPANY_CODE .
MOVE ZADOV_GRAINS_020-APP_CODE TO
ZADOT_GRAINS_020-APP_CODE .
MOVE ZADOV_GRAINS_020-COMMODITY TO
ZADOT_GRAINS_020-COMMODITY .
MOVE ZADOV_GRAINS_020-PROFIT_CENTER TO
ZADOT_GRAINS_020-PROFIT_CENTER .
MOVE ZADOV_GRAINS_020-TRANSITORY_ACCOUNT TO
ZADOT_GRAINS_020-TRANSITORY_ACCOUNT .
MOVE ZADOV_GRAINS_020-MANDT TO
ZADOT_GRAINS_020-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADOT_GRAINS_020'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADOT_GRAINS_020 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADOT_GRAINS_020'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
