*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZADOV_GRAINS_009................................*
FORM GET_DATA_ZADOV_GRAINS_009.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADOT_GRAINS_009 WHERE
(VIM_WHERETAB) .
    CLEAR ZADOV_GRAINS_009 .
ZADOV_GRAINS_009-MANDT =
ZADOT_GRAINS_009-MANDT .
ZADOV_GRAINS_009-COMPANY_CODE =
ZADOT_GRAINS_009-COMPANY_CODE .
ZADOV_GRAINS_009-USERNAME =
ZADOT_GRAINS_009-USERNAME .
ZADOV_GRAINS_009-AUTH_GROUP =
ZADOT_GRAINS_009-AUTH_GROUP .
ZADOV_GRAINS_009-ACTIVE =
ZADOT_GRAINS_009-ACTIVE .
    SELECT SINGLE * FROM ZADOT_GRAINS_008 WHERE
COMPANY_CODE = ZADOT_GRAINS_009-COMPANY_CODE AND
USERNAME = ZADOT_GRAINS_009-USERNAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZADOT_GRAINS_001 WHERE
COMPANY_CODE = ZADOT_GRAINS_008-COMPANY_CODE .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM T001 WHERE
BUKRS = ZADOT_GRAINS_001-COMPANY_CODE .
        IF SY-SUBRC EQ 0.
ZADOV_GRAINS_009-COMPANY_CODE_DESCR =
T001-BUTXT .
        ENDIF.
      ENDIF.
      SELECT SINGLE * FROM USR21 WHERE
BNAME = ZADOT_GRAINS_008-USERNAME .
      IF SY-SUBRC EQ 0.
        SELECT * FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER .
ZADOV_GRAINS_009-NAME_TEXT =
ADRP-NAME_TEXT .
          EXIT.
        ENDSELECT.
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZADOV_GRAINS_009.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADOV_GRAINS_009 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADOV_GRAINS_009.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADOV_GRAINS_009-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADOT_GRAINS_009 WHERE
  COMPANY_CODE = ZADOV_GRAINS_009-COMPANY_CODE AND
  USERNAME = ZADOV_GRAINS_009-USERNAME AND
  AUTH_GROUP = ZADOV_GRAINS_009-AUTH_GROUP .
    IF SY-SUBRC = 0.
    DELETE ZADOT_GRAINS_009 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADOT_GRAINS_009 WHERE
  COMPANY_CODE = ZADOV_GRAINS_009-COMPANY_CODE AND
  USERNAME = ZADOV_GRAINS_009-USERNAME AND
  AUTH_GROUP = ZADOV_GRAINS_009-AUTH_GROUP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADOT_GRAINS_009.
    ENDIF.
ZADOT_GRAINS_009-MANDT =
ZADOV_GRAINS_009-MANDT .
ZADOT_GRAINS_009-COMPANY_CODE =
ZADOV_GRAINS_009-COMPANY_CODE .
ZADOT_GRAINS_009-USERNAME =
ZADOV_GRAINS_009-USERNAME .
ZADOT_GRAINS_009-AUTH_GROUP =
ZADOV_GRAINS_009-AUTH_GROUP .
ZADOT_GRAINS_009-ACTIVE =
ZADOV_GRAINS_009-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZADOT_GRAINS_009 ##WARN_OK.
    ELSE.
    INSERT ZADOT_GRAINS_009 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADOV_GRAINS_009-UPD_FLAG,
STATUS_ZADOV_GRAINS_009-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADOV_GRAINS_009.
  SELECT SINGLE * FROM ZADOT_GRAINS_009 WHERE
COMPANY_CODE = ZADOV_GRAINS_009-COMPANY_CODE AND
USERNAME = ZADOV_GRAINS_009-USERNAME AND
AUTH_GROUP = ZADOV_GRAINS_009-AUTH_GROUP .
ZADOV_GRAINS_009-MANDT =
ZADOT_GRAINS_009-MANDT .
ZADOV_GRAINS_009-COMPANY_CODE =
ZADOT_GRAINS_009-COMPANY_CODE .
ZADOV_GRAINS_009-USERNAME =
ZADOT_GRAINS_009-USERNAME .
ZADOV_GRAINS_009-AUTH_GROUP =
ZADOT_GRAINS_009-AUTH_GROUP .
ZADOV_GRAINS_009-ACTIVE =
ZADOT_GRAINS_009-ACTIVE .
    SELECT SINGLE * FROM ZADOT_GRAINS_008 WHERE
COMPANY_CODE = ZADOT_GRAINS_009-COMPANY_CODE AND
USERNAME = ZADOT_GRAINS_009-USERNAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZADOT_GRAINS_001 WHERE
COMPANY_CODE = ZADOT_GRAINS_008-COMPANY_CODE .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM T001 WHERE
BUKRS = ZADOT_GRAINS_001-COMPANY_CODE .
        IF SY-SUBRC EQ 0.
ZADOV_GRAINS_009-COMPANY_CODE_DESCR =
T001-BUTXT .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZADOV_GRAINS_009-COMPANY_CODE_DESCR .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_009-COMPANY_CODE_DESCR .
      ENDIF.
      SELECT SINGLE * FROM USR21 WHERE
BNAME = ZADOT_GRAINS_008-USERNAME .
      IF SY-SUBRC EQ 0.
        SELECT * FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER .
ZADOV_GRAINS_009-NAME_TEXT =
ADRP-NAME_TEXT .
          EXIT.
        ENDSELECT.
        IF SY-SUBRC NE 0.
          CLEAR SY-SUBRC.
          CLEAR ZADOV_GRAINS_009-NAME_TEXT .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_009-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZADOV_GRAINS_009-COMPANY_CODE_DESCR .
      CLEAR ZADOV_GRAINS_009-NAME_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADOV_GRAINS_009 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADOV_GRAINS_009-COMPANY_CODE TO
ZADOT_GRAINS_009-COMPANY_CODE .
MOVE ZADOV_GRAINS_009-USERNAME TO
ZADOT_GRAINS_009-USERNAME .
MOVE ZADOV_GRAINS_009-AUTH_GROUP TO
ZADOT_GRAINS_009-AUTH_GROUP .
MOVE ZADOV_GRAINS_009-MANDT TO
ZADOT_GRAINS_009-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADOT_GRAINS_009'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADOT_GRAINS_009 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADOT_GRAINS_009'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZADOV_GRAINS_009 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZADOT_GRAINS_009-MANDT =
ZADOV_GRAINS_009-MANDT .
ZADOT_GRAINS_009-COMPANY_CODE =
ZADOV_GRAINS_009-COMPANY_CODE .
ZADOT_GRAINS_009-USERNAME =
ZADOV_GRAINS_009-USERNAME .
ZADOT_GRAINS_009-AUTH_GROUP =
ZADOV_GRAINS_009-AUTH_GROUP .
ZADOT_GRAINS_009-ACTIVE =
ZADOV_GRAINS_009-ACTIVE .
    SELECT SINGLE * FROM ZADOT_GRAINS_008 WHERE
COMPANY_CODE = ZADOT_GRAINS_009-COMPANY_CODE AND
USERNAME = ZADOT_GRAINS_009-USERNAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZADOT_GRAINS_001 WHERE
COMPANY_CODE = ZADOT_GRAINS_008-COMPANY_CODE .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM T001 WHERE
BUKRS = ZADOT_GRAINS_001-COMPANY_CODE .
        IF SY-SUBRC EQ 0.
ZADOV_GRAINS_009-COMPANY_CODE_DESCR =
T001-BUTXT .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZADOV_GRAINS_009-COMPANY_CODE_DESCR .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_009-COMPANY_CODE_DESCR .
      ENDIF.
      SELECT SINGLE * FROM USR21 WHERE
BNAME = ZADOT_GRAINS_008-USERNAME .
      IF SY-SUBRC EQ 0.
        SELECT * FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER .
ZADOV_GRAINS_009-NAME_TEXT =
ADRP-NAME_TEXT .
          EXIT.
        ENDSELECT.
        IF SY-SUBRC NE 0.
          CLEAR SY-SUBRC.
          CLEAR ZADOV_GRAINS_009-NAME_TEXT .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_009-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZADOV_GRAINS_009-COMPANY_CODE_DESCR .
      CLEAR ZADOV_GRAINS_009-NAME_TEXT .
    ENDIF.
ENDFORM.
