*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZADOV_GRAINS_006................................*
FORM GET_DATA_ZADOV_GRAINS_006.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZADOT_GRAINS_006 WHERE
(VIM_WHERETAB) .
    CLEAR ZADOV_GRAINS_006 .
ZADOV_GRAINS_006-MANDT =
ZADOT_GRAINS_006-MANDT .
ZADOV_GRAINS_006-COMPANY_CODE =
ZADOT_GRAINS_006-COMPANY_CODE .
ZADOV_GRAINS_006-APP_CODE =
ZADOT_GRAINS_006-APP_CODE .
ZADOV_GRAINS_006-ID =
ZADOT_GRAINS_006-ID .
ZADOV_GRAINS_006-PROPERTY =
ZADOT_GRAINS_006-PROPERTY .
ZADOV_GRAINS_006-SEMANTIC_OBJECT =
ZADOT_GRAINS_006-SEMANTIC_OBJECT .
ZADOV_GRAINS_006-ACTIVE =
ZADOT_GRAINS_006-ACTIVE .
    SELECT SINGLE * FROM /UI2/SEMOBJ WHERE
SEM_OBJ = ZADOT_GRAINS_006-SEMANTIC_OBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /UI2/SEMOBJT WHERE
SEM_OBJ = /UI2/SEMOBJ-SEM_OBJ AND
LANGUAGE = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-SEMANTIC_OBJECT_DESCR =
/UI2/SEMOBJT-SEM_OBJ_TEXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZADOT_GRAINS_004 WHERE
COMPANY_CODE = ZADOT_GRAINS_006-COMPANY_CODE AND
APP_CODE = ZADOT_GRAINS_006-APP_CODE AND
ID = ZADOT_GRAINS_006-ID .
    IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-DDL_NAME =
ZADOT_GRAINS_004-DDL_NAME .
      SELECT SINGLE * FROM ZADOT_GRAINS_002 WHERE
COMPANY_CODE = ZADOT_GRAINS_004-COMPANY_CODE AND
APP_CODE = ZADOT_GRAINS_004-APP_CODE .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-APP_DESCRIPTION =
ZADOT_GRAINS_002-APP_DESCRIPTION .
        SELECT SINGLE * FROM ZADOT_GRAINS_001 WHERE
COMPANY_CODE = ZADOT_GRAINS_002-COMPANY_CODE .
        IF SY-SUBRC EQ 0.
          SELECT SINGLE * FROM T001 WHERE
BUKRS = ZADOT_GRAINS_001-COMPANY_CODE .
          IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-COMPANY_CODE_DESCR =
T001-BUTXT .
          ENDIF.
        ENDIF.
      ENDIF.
      SELECT SINGLE * FROM DDDDLSRCT WHERE
DDLNAME = ZADOT_GRAINS_004-DDL_NAME AND
DDLANGUAGE = 'P' AND
AS4LOCAL = 'A' .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-DDL_NAME_DESCR =
DDDDLSRCT-DDTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZADOV_GRAINS_006.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZADOV_GRAINS_006 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZADOV_GRAINS_006.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZADOV_GRAINS_006-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZADOT_GRAINS_006 WHERE
  COMPANY_CODE = ZADOV_GRAINS_006-COMPANY_CODE AND
  APP_CODE = ZADOV_GRAINS_006-APP_CODE AND
  ID = ZADOV_GRAINS_006-ID AND
  PROPERTY = ZADOV_GRAINS_006-PROPERTY .
    IF SY-SUBRC = 0.
    DELETE ZADOT_GRAINS_006 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZADOT_GRAINS_006 WHERE
  COMPANY_CODE = ZADOV_GRAINS_006-COMPANY_CODE AND
  APP_CODE = ZADOV_GRAINS_006-APP_CODE AND
  ID = ZADOV_GRAINS_006-ID AND
  PROPERTY = ZADOV_GRAINS_006-PROPERTY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZADOT_GRAINS_006.
    ENDIF.
ZADOT_GRAINS_006-MANDT =
ZADOV_GRAINS_006-MANDT .
ZADOT_GRAINS_006-COMPANY_CODE =
ZADOV_GRAINS_006-COMPANY_CODE .
ZADOT_GRAINS_006-APP_CODE =
ZADOV_GRAINS_006-APP_CODE .
ZADOT_GRAINS_006-ID =
ZADOV_GRAINS_006-ID .
ZADOT_GRAINS_006-PROPERTY =
ZADOV_GRAINS_006-PROPERTY .
ZADOT_GRAINS_006-SEMANTIC_OBJECT =
ZADOV_GRAINS_006-SEMANTIC_OBJECT .
ZADOT_GRAINS_006-ACTIVE =
ZADOV_GRAINS_006-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZADOT_GRAINS_006 ##WARN_OK.
    ELSE.
    INSERT ZADOT_GRAINS_006 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZADOV_GRAINS_006-UPD_FLAG,
STATUS_ZADOV_GRAINS_006-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZADOV_GRAINS_006.
  SELECT SINGLE * FROM ZADOT_GRAINS_006 WHERE
COMPANY_CODE = ZADOV_GRAINS_006-COMPANY_CODE AND
APP_CODE = ZADOV_GRAINS_006-APP_CODE AND
ID = ZADOV_GRAINS_006-ID AND
PROPERTY = ZADOV_GRAINS_006-PROPERTY .
ZADOV_GRAINS_006-MANDT =
ZADOT_GRAINS_006-MANDT .
ZADOV_GRAINS_006-COMPANY_CODE =
ZADOT_GRAINS_006-COMPANY_CODE .
ZADOV_GRAINS_006-APP_CODE =
ZADOT_GRAINS_006-APP_CODE .
ZADOV_GRAINS_006-ID =
ZADOT_GRAINS_006-ID .
ZADOV_GRAINS_006-PROPERTY =
ZADOT_GRAINS_006-PROPERTY .
ZADOV_GRAINS_006-SEMANTIC_OBJECT =
ZADOT_GRAINS_006-SEMANTIC_OBJECT .
ZADOV_GRAINS_006-ACTIVE =
ZADOT_GRAINS_006-ACTIVE .
    SELECT SINGLE * FROM /UI2/SEMOBJ WHERE
SEM_OBJ = ZADOT_GRAINS_006-SEMANTIC_OBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /UI2/SEMOBJT WHERE
SEM_OBJ = /UI2/SEMOBJ-SEM_OBJ AND
LANGUAGE = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-SEMANTIC_OBJECT_DESCR =
/UI2/SEMOBJT-SEM_OBJ_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_006-SEMANTIC_OBJECT_DESCR .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZADOV_GRAINS_006-SEMANTIC_OBJECT_DESCR .
    ENDIF.
    SELECT SINGLE * FROM ZADOT_GRAINS_004 WHERE
COMPANY_CODE = ZADOT_GRAINS_006-COMPANY_CODE AND
APP_CODE = ZADOT_GRAINS_006-APP_CODE AND
ID = ZADOT_GRAINS_006-ID .
    IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-DDL_NAME =
ZADOT_GRAINS_004-DDL_NAME .
      SELECT SINGLE * FROM ZADOT_GRAINS_002 WHERE
COMPANY_CODE = ZADOT_GRAINS_004-COMPANY_CODE AND
APP_CODE = ZADOT_GRAINS_004-APP_CODE .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-APP_DESCRIPTION =
ZADOT_GRAINS_002-APP_DESCRIPTION .
        SELECT SINGLE * FROM ZADOT_GRAINS_001 WHERE
COMPANY_CODE = ZADOT_GRAINS_002-COMPANY_CODE .
        IF SY-SUBRC EQ 0.
          SELECT SINGLE * FROM T001 WHERE
BUKRS = ZADOT_GRAINS_001-COMPANY_CODE .
          IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-COMPANY_CODE_DESCR =
T001-BUTXT .
          ELSE.
            CLEAR SY-SUBRC.
            CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
          ENDIF.
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_006-APP_DESCRIPTION .
        CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
      ENDIF.
      SELECT SINGLE * FROM DDDDLSRCT WHERE
DDLNAME = ZADOT_GRAINS_004-DDL_NAME AND
DDLANGUAGE = 'P' AND
AS4LOCAL = 'A' .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-DDL_NAME_DESCR =
DDDDLSRCT-DDTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_006-DDL_NAME_DESCR .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZADOV_GRAINS_006-DDL_NAME .
      CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
      CLEAR ZADOV_GRAINS_006-APP_DESCRIPTION .
      CLEAR ZADOV_GRAINS_006-DDL_NAME_DESCR .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZADOV_GRAINS_006 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZADOV_GRAINS_006-COMPANY_CODE TO
ZADOT_GRAINS_006-COMPANY_CODE .
MOVE ZADOV_GRAINS_006-APP_CODE TO
ZADOT_GRAINS_006-APP_CODE .
MOVE ZADOV_GRAINS_006-ID TO
ZADOT_GRAINS_006-ID .
MOVE ZADOV_GRAINS_006-PROPERTY TO
ZADOT_GRAINS_006-PROPERTY .
MOVE ZADOV_GRAINS_006-MANDT TO
ZADOT_GRAINS_006-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZADOT_GRAINS_006'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZADOT_GRAINS_006 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZADOT_GRAINS_006'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZADOV_GRAINS_006 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZADOT_GRAINS_006-MANDT =
ZADOV_GRAINS_006-MANDT .
ZADOT_GRAINS_006-COMPANY_CODE =
ZADOV_GRAINS_006-COMPANY_CODE .
ZADOT_GRAINS_006-APP_CODE =
ZADOV_GRAINS_006-APP_CODE .
ZADOT_GRAINS_006-ID =
ZADOV_GRAINS_006-ID .
ZADOT_GRAINS_006-PROPERTY =
ZADOV_GRAINS_006-PROPERTY .
ZADOT_GRAINS_006-SEMANTIC_OBJECT =
ZADOV_GRAINS_006-SEMANTIC_OBJECT .
ZADOT_GRAINS_006-ACTIVE =
ZADOV_GRAINS_006-ACTIVE .
    SELECT SINGLE * FROM /UI2/SEMOBJ WHERE
SEM_OBJ = ZADOT_GRAINS_006-SEMANTIC_OBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM /UI2/SEMOBJT WHERE
SEM_OBJ = /UI2/SEMOBJ-SEM_OBJ AND
LANGUAGE = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-SEMANTIC_OBJECT_DESCR =
/UI2/SEMOBJT-SEM_OBJ_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_006-SEMANTIC_OBJECT_DESCR .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZADOV_GRAINS_006-SEMANTIC_OBJECT_DESCR .
    ENDIF.
    SELECT SINGLE * FROM ZADOT_GRAINS_004 WHERE
COMPANY_CODE = ZADOT_GRAINS_006-COMPANY_CODE AND
APP_CODE = ZADOT_GRAINS_006-APP_CODE AND
ID = ZADOT_GRAINS_006-ID .
    IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-DDL_NAME =
ZADOT_GRAINS_004-DDL_NAME .
      SELECT SINGLE * FROM ZADOT_GRAINS_002 WHERE
COMPANY_CODE = ZADOT_GRAINS_004-COMPANY_CODE AND
APP_CODE = ZADOT_GRAINS_004-APP_CODE .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-APP_DESCRIPTION =
ZADOT_GRAINS_002-APP_DESCRIPTION .
        SELECT SINGLE * FROM ZADOT_GRAINS_001 WHERE
COMPANY_CODE = ZADOT_GRAINS_002-COMPANY_CODE .
        IF SY-SUBRC EQ 0.
          SELECT SINGLE * FROM T001 WHERE
BUKRS = ZADOT_GRAINS_001-COMPANY_CODE .
          IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-COMPANY_CODE_DESCR =
T001-BUTXT .
          ELSE.
            CLEAR SY-SUBRC.
            CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
          ENDIF.
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_006-APP_DESCRIPTION .
        CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
      ENDIF.
      SELECT SINGLE * FROM DDDDLSRCT WHERE
DDLNAME = ZADOT_GRAINS_004-DDL_NAME AND
DDLANGUAGE = 'P' AND
AS4LOCAL = 'A' .
      IF SY-SUBRC EQ 0.
ZADOV_GRAINS_006-DDL_NAME_DESCR =
DDDDLSRCT-DDTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZADOV_GRAINS_006-DDL_NAME_DESCR .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZADOV_GRAINS_006-DDL_NAME .
      CLEAR ZADOV_GRAINS_006-COMPANY_CODE_DESCR .
      CLEAR ZADOV_GRAINS_006-APP_DESCRIPTION .
      CLEAR ZADOV_GRAINS_006-DDL_NAME_DESCR .
    ENDIF.
ENDFORM.
